import type { TechnologyDefinition } from '@scalelab/model';
import { cacheConfig, exp, logn, relationalDbConfig } from '../defaults';
import { tech } from './clients';

export const dataTechnologies: TechnologyDefinition[] = [
  tech({
    id: 'redis',
    name: 'Redis',
    category: 'cache',
    archetype: 'cache',
    icon: 'redis',
    brandColor: '#DC382D',
    description: 'In-memory key-value store, commonly used as a cache.',
    tags: ['key-value', 'in-memory'],
    defaults: cacheConfig({ readLatency: exp(1), writeLatency: exp(1.5) }),
  }),
  tech({
    id: 'valkey',
    name: 'Valkey',
    category: 'cache',
    archetype: 'cache',
    icon: 'valkey',
    brandColor: '#6983FF',
    description: 'Open-source, Redis-compatible in-memory data store.',
    tags: ['key-value', 'in-memory', 'redis-compatible'],
    defaults: cacheConfig({ readLatency: exp(1), writeLatency: exp(1.5) }),
  }),
  tech({
    id: 'memcached',
    name: 'Memcached',
    category: 'cache',
    archetype: 'cache',
    icon: 'memcached',
    brandColor: '#5A8F3C',
    description: 'Simple, fast distributed memory cache.',
    tags: ['key-value', 'in-memory'],
    defaults: cacheConfig({ readLatency: exp(0.8), writeLatency: exp(1) }),
  }),
  tech({
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'relational-db',
    archetype: 'relational-db',
    icon: 'postgresql',
    brandColor: '#336791',
    description: 'Advanced open-source relational database.',
    tags: ['sql', 'acid'],
    defaults: relationalDbConfig({ connectionPool: 100, readQuery: logn(8, 40), writeQuery: logn(15, 80) }),
  }),
  tech({
    id: 'mysql',
    name: 'MySQL',
    category: 'relational-db',
    archetype: 'relational-db',
    icon: 'mysql',
    brandColor: '#4479A1',
    description: 'Popular open-source relational database.',
    tags: ['sql', 'acid'],
    defaults: relationalDbConfig({ connectionPool: 150, readQuery: logn(7, 35), writeQuery: logn(14, 70) }),
  }),
  tech({
    id: 'aurora-postgres',
    name: 'Amazon Aurora',
    category: 'relational-db',
    archetype: 'relational-db',
    icon: 'amazonrds',
    brandColor: '#527FFF',
    description: 'Managed PostgreSQL- and MySQL-compatible database on AWS.',
    tags: ['sql', 'aws', 'managed'],
    defaults: relationalDbConfig({ connectionPool: 200, readQuery: logn(6, 30), writeQuery: logn(12, 60) }),
  }),
];
