import type { TechnologyDefinition } from '@scalelab/model';
import { externalConfig, logn } from '../defaults';
import { tech } from './clients';

/**
 * Third-party services. Defaults are starting assumptions for a healthy provider,
 * not measurements; tune them to match the provider's status page or your own logs.
 * Timeouts are the dangerous case: the provider did the work, but your service gave up waiting.
 */
export const externalTechnologies: TechnologyDefinition[] = [
  tech({
    id: 'stripe',
    name: 'Stripe',
    category: 'external',
    archetype: 'external-api',
    icon: 'stripe',
    brandColor: '#635BFF',
    description: 'Payments API. Live mode allows about 100 requests per second by default.',
    tags: ['payments', 'third-party'],
    defaults: externalConfig({ latency: logn(350, 1500), errorRate: 0.005, timeoutRate: 0.002, timeoutMs: 5000, rateLimitRps: 100 }),
  }),
  tech({
    id: 'paypal',
    name: 'PayPal',
    category: 'external',
    archetype: 'external-api',
    icon: 'paypal',
    brandColor: '#003087',
    description: 'Payments API.',
    tags: ['payments', 'third-party'],
    defaults: externalConfig({ latency: logn(500, 2000), errorRate: 0.008, timeoutRate: 0.003 }),
  }),
  tech({
    id: 'razorpay',
    name: 'Razorpay',
    category: 'external',
    archetype: 'external-api',
    icon: 'razorpay',
    brandColor: '#0C2451',
    description: 'Payments API, popular in India.',
    tags: ['payments', 'third-party', 'india', 'upi'],
    defaults: externalConfig({ latency: logn(400, 2000), errorRate: 0.008, timeoutRate: 0.003 }),
  }),
  tech({
    id: 'twilio',
    name: 'Twilio',
    category: 'external',
    archetype: 'external-api',
    icon: 'twilio',
    brandColor: '#F22F46',
    description: 'SMS, voice and verification API.',
    tags: ['sms', 'otp', 'third-party'],
    defaults: externalConfig({ latency: logn(250, 1000), errorRate: 0.003, timeoutRate: 0.001 }),
  }),
  tech({
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'external',
    archetype: 'external-api',
    icon: 'sendgrid',
    brandColor: '#1A82E2',
    description: 'Email delivery API.',
    tags: ['email', 'third-party'],
    defaults: externalConfig({ latency: logn(200, 800), errorRate: 0.003, timeoutRate: 0.001 }),
  }),
  tech({
    id: 'openai-api',
    name: 'OpenAI API',
    category: 'external',
    archetype: 'external-api',
    icon: 'openai',
    brandColor: '#412991',
    description: 'LLM API. Slow, with a long tail; set the rate limit from your account tier.',
    tags: ['ai', 'llm', 'third-party'],
    defaults: externalConfig({ latency: logn(1500, 8000), errorRate: 0.01, timeoutRate: 0.005, timeoutMs: 30_000 }),
  }),
  tech({
    id: 'third-party-api',
    name: 'Third-party API',
    category: 'external',
    archetype: 'external-api',
    icon: 'api',
    brandColor: '#64748B',
    description: 'Any API you call but don’t run: shipping rates, tax, maps, KYC.',
    tags: ['third-party', 'http'],
    defaults: externalConfig({ latency: logn(200, 1000), errorRate: 0.01, timeoutRate: 0.005, timeoutMs: 3000 }),
  }),
  tech({
    id: 'auth0',
    name: 'Auth0',
    category: 'auth',
    archetype: 'auth-provider',
    icon: 'auth0',
    brandColor: '#EB5424',
    description: 'Hosted login and token service.',
    tags: ['auth', 'login', 'oauth', 'third-party'],
    defaults: externalConfig({ latency: logn(150, 600), errorRate: 0.002, timeoutRate: 0.001, timeoutMs: 3000 }),
  }),
  tech({
    id: 'clerk',
    name: 'Clerk',
    category: 'auth',
    archetype: 'auth-provider',
    icon: 'clerk',
    brandColor: '#6C47FF',
    description: 'Hosted authentication and user management.',
    tags: ['auth', 'login', 'third-party'],
    defaults: externalConfig({ latency: logn(120, 500), errorRate: 0.002, timeoutRate: 0.001, timeoutMs: 3000 }),
  }),
];
