import type { LibraryDefinition } from '@scalelab/model';
import { exp } from '../defaults';

const FRONTENDS = ['nextjs', 'react', 'vue', 'angular'];
const REACT_LIKE = ['nextjs', 'react'];
const NODE_BACKENDS = ['nestjs', 'express'];
const ALL_BACKENDS = ['spring-boot', 'nestjs', 'express', 'django', 'fastapi', 'go-gin', 'aspnet-core'];

export const libraries: LibraryDefinition[] = [
  // ── Frontend (no server-side simulation effect) ──
  {
    id: 'tailwind-css',
    name: 'Tailwind CSS',
    category: 'styling',
    icon: 'tailwindcss',
    brandColor: '#38BDF8',
    compatibleWith: FRONTENDS,
    conflictsWith: [],
    effect: { kind: 'none' },
  },
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui',
    category: 'ui-kit',
    icon: 'shadcnui',
    brandColor: '#000000',
    compatibleWith: REACT_LIKE,
    conflictsWith: ['mui'],
    effect: { kind: 'none' },
  },
  {
    id: 'mui',
    name: 'MUI',
    category: 'ui-kit',
    icon: 'mui',
    brandColor: '#007FFF',
    compatibleWith: REACT_LIKE,
    conflictsWith: ['shadcn-ui'],
    effect: { kind: 'none' },
  },
  {
    id: 'zustand',
    name: 'Zustand',
    category: 'state',
    icon: 'zustand',
    brandColor: '#433E38',
    compatibleWith: REACT_LIKE,
    conflictsWith: ['redux-toolkit'],
    effect: { kind: 'none' },
  },
  {
    id: 'redux-toolkit',
    name: 'Redux Toolkit',
    category: 'state',
    icon: 'redux',
    brandColor: '#764ABC',
    compatibleWith: REACT_LIKE,
    conflictsWith: ['zustand'],
    effect: { kind: 'none' },
  },
  {
    id: 'tanstack-query',
    name: 'TanStack Query',
    category: 'data-fetching',
    icon: 'reactquery',
    brandColor: '#FF4154',
    compatibleWith: ['nextjs', 'react', 'vue'],
    conflictsWith: ['swr'],
    effect: { kind: 'none' },
  },
  {
    id: 'swr',
    name: 'SWR',
    category: 'data-fetching',
    icon: 'swr',
    brandColor: '#000000',
    compatibleWith: REACT_LIKE,
    conflictsWith: ['tanstack-query'],
    effect: { kind: 'none' },
  },
  {
    id: 'nextauth',
    name: 'Auth.js (NextAuth)',
    category: 'auth',
    icon: 'authdotjs',
    brandColor: '#7C3AED',
    compatibleWith: ['nextjs'],
    conflictsWith: [],
    effect: { kind: 'none' },
  },
  {
    id: 'motion',
    name: 'Motion',
    category: 'animation',
    icon: 'framer',
    brandColor: '#FFF312',
    compatibleWith: REACT_LIKE,
    conflictsWith: [],
    effect: { kind: 'none' },
  },

  // ── Spring Boot ──
  {
    id: 'spring-data-jpa',
    name: 'Spring Data JPA',
    category: 'orm',
    icon: 'spring',
    brandColor: '#59666C',
    compatibleWith: ['spring-boot'],
    conflictsWith: [],
    effect: { kind: 'add-overhead', perRequestMs: 2 },
  },
  {
    id: 'spring-security',
    name: 'Spring Security',
    category: 'auth',
    icon: 'springsecurity',
    brandColor: '#6DB33F',
    compatibleWith: ['spring-boot'],
    conflictsWith: [],
    effect: { kind: 'auth-step', latency: exp(1.5) },
  },
  {
    id: 'resilience4j',
    name: 'Resilience4j',
    category: 'resilience',
    icon: 'resilience4j',
    brandColor: '#2B9348',
    compatibleWith: ['spring-boot'],
    conflictsWith: [],
    effect: { kind: 'enable-resilience', retries: true, circuitBreaker: true, timeouts: true },
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    category: 'cache-client',
    icon: 'redis',
    brandColor: '#E5484D',
    compatibleWith: ['spring-boot'],
    conflictsWith: [],
    effect: { kind: 'connection-pool', target: 'cache', poolSize: 50 },
  },
  {
    id: 'hikaricp',
    name: 'HikariCP',
    category: 'orm',
    icon: 'hikaricp',
    brandColor: '#1F6FEB',
    compatibleWith: ['spring-boot'],
    conflictsWith: [],
    effect: { kind: 'connection-pool', target: 'relational-db', poolSize: 10 },
  },

  // ── Node.js backends ──
  {
    id: 'prisma',
    name: 'Prisma',
    category: 'orm',
    icon: 'prisma',
    brandColor: '#2D3748',
    compatibleWith: [...NODE_BACKENDS, 'nextjs'],
    conflictsWith: ['typeorm'],
    effect: { kind: 'add-overhead', perRequestMs: 2 },
  },
  {
    id: 'typeorm',
    name: 'TypeORM',
    category: 'orm',
    icon: 'typeorm',
    brandColor: '#FE0803',
    compatibleWith: NODE_BACKENDS,
    conflictsWith: ['prisma'],
    effect: { kind: 'add-overhead', perRequestMs: 3 },
  },
  {
    id: 'passport',
    name: 'Passport.js',
    category: 'auth',
    icon: 'passport',
    brandColor: '#34E27A',
    compatibleWith: NODE_BACKENDS,
    conflictsWith: [],
    effect: { kind: 'auth-step', latency: exp(1) },
  },
  {
    id: 'ioredis',
    name: 'ioredis',
    category: 'cache-client',
    icon: 'redis',
    brandColor: '#DC382D',
    compatibleWith: NODE_BACKENDS,
    conflictsWith: [],
    effect: { kind: 'connection-pool', target: 'cache', poolSize: 50 },
  },
  {
    id: 'zod',
    name: 'Zod',
    category: 'validation',
    icon: 'zod',
    brandColor: '#3E67B1',
    compatibleWith: [...NODE_BACKENDS, 'nextjs'],
    conflictsWith: [],
    effect: { kind: 'add-overhead', perRequestMs: 0.3 },
  },

  // ── Python ──
  {
    id: 'sqlalchemy',
    name: 'SQLAlchemy',
    category: 'orm',
    icon: 'sqlalchemy',
    brandColor: '#D71F00',
    compatibleWith: ['fastapi'],
    conflictsWith: [],
    effect: { kind: 'add-overhead', perRequestMs: 3 },
  },
  {
    id: 'django-orm',
    name: 'Django ORM',
    category: 'orm',
    icon: 'django',
    brandColor: '#0C4B33',
    compatibleWith: ['django'],
    conflictsWith: [],
    effect: { kind: 'add-overhead', perRequestMs: 3 },
  },

  // ── Cross-cutting ──
  {
    id: 'opentelemetry-sdk',
    name: 'OpenTelemetry SDK',
    category: 'observability',
    icon: 'opentelemetry',
    brandColor: '#F5A800',
    compatibleWith: ALL_BACKENDS,
    conflictsWith: [],
    effect: { kind: 'rich-tracing' },
  },
];
