// Generated from the catalog's icon slugs. Logos come from Simple Icons (CC0);
// they identify each technology and belong to their respective owners.
// Slugs without a Simple Icons logo fall back to a lettered badge in the UI.
import {
  siAndroid,
  siAngular,
  siApachecassandra,
  siApachekafka,
  siAuth0,
  siCelery,
  siClerk,
  siCloudflare,
  siDatadog,
  siDjango,
  siDotnet,
  siElasticsearch,
  siExpress,
  siFastapi,
  siFirebase,
  siFramer,
  siGo,
  siGooglechrome,
  siKong,
  siKubernetes,
  siMongodb,
  siMui,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNginx,
  siOpentelemetry,
  siPassport,
  siPaypal,
  siPostgresql,
  siPrisma,
  siPrometheus,
  siRabbitmq,
  siRazorpay,
  siReact,
  siReactquery,
  siRedis,
  siRedux,
  siShadcnui,
  siSidekiq,
  siSocketdotio,
  siSpring,
  siSpringboot,
  siSpringsecurity,
  siSqlalchemy,
  siStripe,
  siSwr,
  siTailwindcss,
  siTypeorm,
  siVuedotjs,
  siZod,
} from 'simple-icons';

export interface IconData {
  path: string;
  hex: string;
}

export const ICONS: Record<string, IconData> = {
  android: siAndroid,
  angular: siAngular,
  apachecassandra: siApachecassandra,
  apachekafka: siApachekafka,
  auth0: siAuth0,
  celery: siCelery,
  clerk: siClerk,
  cloudflare: siCloudflare,
  datadog: siDatadog,
  django: siDjango,
  dotnet: siDotnet,
  elasticsearch: siElasticsearch,
  express: siExpress,
  fastapi: siFastapi,
  firebase: siFirebase,
  framer: siFramer,
  go: siGo,
  googlechrome: siGooglechrome,
  kong: siKong,
  kubernetes: siKubernetes,
  mongodb: siMongodb,
  mui: siMui,
  mysql: siMysql,
  nestjs: siNestjs,
  nextdotjs: siNextdotjs,
  nginx: siNginx,
  opentelemetry: siOpentelemetry,
  passport: siPassport,
  paypal: siPaypal,
  postgresql: siPostgresql,
  prisma: siPrisma,
  prometheus: siPrometheus,
  rabbitmq: siRabbitmq,
  razorpay: siRazorpay,
  react: siReact,
  reactquery: siReactquery,
  redis: siRedis,
  redux: siRedux,
  shadcnui: siShadcnui,
  sidekiq: siSidekiq,
  socketdotio: siSocketdotio,
  spring: siSpring,
  springboot: siSpringboot,
  springsecurity: siSpringsecurity,
  sqlalchemy: siSqlalchemy,
  stripe: siStripe,
  swr: siSwr,
  tailwindcss: siTailwindcss,
  typeorm: siTypeorm,
  vuedotjs: siVuedotjs,
  zod: siZod,
};
